import {nav, RouteScreen} from '../../nav'
import useUser from '../../../hooks/useUser'
import JSONEditor from '../../elements/JSONEditor'
import {UserVO} from 'iso/src/store/bootstrap/repos/user-schema'
import UserEditor from '../../elements/UserEditor'
import InnerPageBase from '../../app/InnerPageBase'
import {useHistory} from 'react-router'
import useFrontDispatch from '../../../hooks/common/useFrontDispatch'
import {addressesCrud, usersCrud} from 'iso/src/store/bootstrap'
import {routerDuck} from '../../../store/ducks/routerDuck'
import {Breadcrumb} from 'antd'
import React from 'react'
import {getAbbrName} from 'iso/src/store/bootstrap/repos/users-crud'
import {UserOutlined} from '@ant-design/icons'
import {AntdIcons} from '../../elements/AntdIcons'
import {useSelector} from 'react-redux'
import {AddressVO} from 'iso/src/store/bootstrap/repos/addresses-schema'
import ClientEditor from '../../elements/AddressEditor'
import useSaveItem from '../../../hooks/useSaveItem'
import {createEditorPage} from '../createEditorPage'
import AddressEditor from '../../elements/AddressEditor'

export const AddressItemPage = createEditorPage({crud: addressesCrud, Editor: AddressEditor,icon: <AntdIcons.HolderOutlined/>})
