type: object
additionalProperties: false

required:
  - MONGO_URI
  - POSTGRES_URI
  - PORT

properties:
  MONGO_URI:
    type: string
  POSTGRES_URI:
    type: string
  WRITE_PG:
    type: boolean
  LOG_ROCKET:
    type: string
  PORT:
    type: number

definitions:
  Port:
    type: integer
    minimum: 0
    maximum: 65535