# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: dev-ssh-deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_pull:
    if: github.ref_type == 'branch'
    name: run pull
    runs-on: ubuntu-latest

    steps:
    - name: install ssh keys
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY_GITHUB_RUNNER }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ vars.DEV_HOST }} > ~/.ssh/known_hosts
    - name: Branch name
      run: echo running on branch ${GITHUB_REF_NAME}  ref type ${GITHUB_REF_TYPE}
    - name: ssh-connect and pull
      run: ssh root@${{ vars.DEV_HOST }} "cd /home/${{ github.event.repository.name }}_${GITHUB_REF_NAME} && git checkout ${GITHUB_REF_NAME} && git checkout ./ && git pull && yarn install"
    - name: ssh-connect restart service
      run: | 
        ssh root@${{ vars.DEV_HOST }} "pm2 restart ${{ github.event.repository.name }}_${GITHUB_REF_NAME}:service --update-env"
    - name: ssh-connect restart front
      run: |
        ssh root@${{ vars.DEV_HOST }} "pm2 restart ${{ github.event.repository.name }}_${GITHUB_REF_NAME}:front --update-env"
    - name: cleanup
      run: rm -rf ~/.ssh

